### ISSUE TITLE
Grunt Error on clean repo clone

### ISSUE THREAD

**Issue by pdavid0** [sails101/even-more-passport#1]
Thanks for this demo ! The demo works but : 

```
info: Starting app...
error: Grunt :: module.js:340
throw err;
      ^
Error: Cannot find module '/Users/philippe/Documents/workspace/even-more-passport/node_modules/sails/node_modules/grunt-cli/bin/grunt'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:906:3
```

Tried to re-install SailsJS and Grunt-Cl but it didn't do anything.

**Comment by yedhukrishnan** [comment]
Is the server running when you do `sails lift`, even if it is throwing error?

I was able to reproduce the error. Have a look at this stackoverflow question and answers: [Getting grunt error on sails lift](http://stackoverflow.com/questions/25453807/getting-grunt-error-on-sails-lift). I think this would help to resolve the issue for now. 

I am looking into this issue to know why this is happening.

**Comment by pdavid0** [comment]
The accepted answer didn't work, but as the second answer point out : 

```
"I had to go into my_project_directory/node_modules/sails and run npm install grunt-cli"
```

No error message now, thanks for the support !
