### ISSUE TITLE
Error in Installation Step 2 part 4

### ISSUE THREAD

**Issue by faktaochkunskap** [sails101/even-more-passport#11]
Running generator (sails-generate-auth) @ `/Users/test/Documents/Jollyrogers/Sails/passport`...
error: Something else already exists at ::/Users/test/Documents/Jollyrogers/Sails/passport/views/auth/login.ejs

**Comment by faktaochkunskap** [comment]
Ok, now I start to understand. Installation step 2 - 6 is already configured. Therefore one does not need to run sails generate auth. But it is good to have the list of the steps for one that are doing this from scratch or learning. A bit confusing though.

**Comment by yedhukrishnan** [comment]
The repo contains a working example for demo. The steps are for your own project.
