### ISSUE TITLE
Grunt error 

### ISSUE THREAD

**Issue by faktaochkunskap** [sails101/even-more-passport#19]
Now I am lost!

sails lift
debug: Deprecation warning: Support for `sails.config.sockets.onConnect` will be removed in an upcoming release. See the v0.11 migration guide for more information and alternate options.
debug: Deprecation warning: `sails.config.sockets.onDisconnect` is now `sails.config.sockets.afterDisconnect`
Setting it for you this time, but note that the new `afterDisconnect` now receives an additional final argument (a callback).
More info: http://sailsjs.org/#/documentation/reference/sails.config/sails.config.sockets.html
debug: Deprecation warning: `sails.config.sockets.authorization` is now `sails.config.sockets.beforeConnect` (setting it for you this time)
## error: 

grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started

---

error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error: 
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
error: 
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error: 
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `/Users/test/Documents/Jollyrogers/Sails/passport/.tmp` ?
error: 
error:      If you think this might be the case, try running:
error:      sudo chown -R 501 /Users/test/Documents/Jollyrogers/Sails/passport/.tmp

error: Trying to use unknown adapter, "sails-postgresql", in model `passport`.
error: Are you sure that adapter is installed in this Sails app?
error: If you wrote a custom adapter with identity="sails-postgresql", it should be in this app's adapters directory.
error: Otherwise, if you're trying to use an adapter named `sails-postgresql`, please run `npm install sails-postgresql@0.11.x`

**Comment by faktaochkunskap** [comment]
Running: npm install

**Comment by shbm1505** [comment]
I have the same issue.....please somebody help!
