### ISSUE TITLE
error with sails lift

### ISSUE THREAD

**Issue by shbm1505** [sails101/even-more-passport#21]
debug: Deprecation warning: Support for `sails.config.sockets.onConnect` will be removed in an upcoming release. See the v0.11 migration guide for more information and alternate options.
debug: Deprecation warning: `sails.config.sockets.onDisconnect` is now `sails.config.sockets.afterDisconnect`
Setting it for you this time, but note that the new `afterDisconnect` now receives an additional final argument (a callback).
More info: http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.sockets.html
debug: Deprecation warning: `sails.config.sockets.authorization` is now `sails.config.sockets.beforeConnect` (setting it for you this time)
debug: Deprecation warning: `sails.config.sockets.beforeConnect` does not allow the `true` setting anymore (setting it to `undefined` for you this time)
warn: `sails.config.express` is deprecated; use `sails.config.http` instead.

/usr/lib/node_modules/agenda/node_modules/mongodb/lib/mongodb/mongo_client.js:409
          throw err
                ^
[object Object]

I am configuring my backened on nodejs.....on command "sails lift" , I am getting the above error.Please somebody help.

**Comment by yedhukrishnan** [comment]
@shbm1505 I've updated sails version to `0.11..0` and removed all depricated methods from `config/sockets.js`. I guess the problems are resolved now :grinning:
