### ISSUE TITLE
Error with google oauth

### ISSUE THREAD

**Issue by hverlin** [sails101/even-more-passport#22]
Hi ! This tutorial is very nice. Thank you.

Everything seems to work (passport local and Facebook work at least) but I have an issue when using Google oAuth. When I click the button in order to authentificate with google, I am redirected to the Google Authorization page and I can login successfully, but then it redirects me to the `/login` page and the user is not created.

Here is my configuration `config/passport.js` :

``` JS
google: {
    name: 'Google',
    protocol: 'oauth2',
    strategy: require('passport-google-oauth').OAuth2Strategy,
    options: {
      clientID: '*************',
      clientSecret: '*************',
      callbackURL: "http://localhost:1337/auth/google/callback",
    },
    scope: ['profile', 'email']
  },
```

and here is the model for the user : 

``` JS
var User = {
  // Enforce model schema in the case of schemaless databases
  schema: true,

  attributes: {
    username  : { type: 'string', unique: true },
    email     : { type: 'email',  unique: true },
    passports : { collection: 'Passport', via: 'user' }
  }
};

module.exports = User;
```

Do you have any idea that can help me to solve this problem? Thank you !

**Comment by tommykennedy** [comment]
My configuration is here and doesn't have the callbackurl. Just tested it and it works. Within the google developer console I have http://localhost as the permitted redirect_uris. 

```
google: {
    name: 'Google',
    protocol: 'oauth2',
    strategy: require('passport-google-oauth').OAuth2Strategy,
    options: {
        clientID: 'x',
        clientSecret: 'x'
    },
    scope: ['email']
},
```

**Comment by yedhukrishnan** [comment]
@tommykennedy Thanks for the help :)
@hverlin Are you still facing the issue?
