### ISSUE TITLE
missing dep in readme

### ISSUE THREAD

**Issue by chadfurman** [sails101/even-more-passport#24]
passport-http-bearer is also required

**Comment by yedhukrishnan** [comment]
`passport-http-bearer` is already there in `package.json`. I didn't get your exact concern.

**Comment by cenobitedk** [comment]
@yedhukrishnan `passport-http-bearer` is not mentioned in the readme but yes it's in `package.json`. :-)

**Comment by yedhukrishnan** [comment]
@ShadeLotus @cenobitedk Sorry about that.. I'll add it to the readme :)

I've added that :)

**Comment by cenobitedk** [comment]
Great! I believe this issue is resolved. :+1:

**Comment by yedhukrishnan** [comment]
@cenobitedk Awesome! Let me know if you face any other problems.
