### ISSUE TITLE
Step 5. Modify config/sessionAuth.js file not found

### ISSUE THREAD

**Issue by jainitya** [sails101/even-more-passport#3]
Hi following  your step given in readme.md ,at step 5 it is "Step 5. Modify config/sessionAuth.js to set the policy for controller actions:" .bit confusion here for me .is it api/policies/sessionAuth.js Or we need to create a new file in config folder name as sessionAuth.js??
Thanks

**Comment by yedhukrishnan** [comment]
Sorry about that! That was a small mistake in the documentation. It is actually `api/policies/sessionAuth.js`. Sorry about that previous misleading reply.

Our dear friend @jurajpetrik pointed it out and helped us to resolve the issue :)
