### ISSUE TITLE
API authorization

### ISSUE THREAD

**Issue by jurajpetrik** [sails101/even-more-passport#6]
regarding this instructions:
For API authorization, add bearerAuth the policy for controller actions that are accessed via API in config/policies.js:

'flash': {
 'remoteHome': ['passport', 'bearerAuth']
},

Following all the steps before there is no bearerAuth policy created. I'm now checking a previous version of this tutorial and trying like that.

**Comment by yedhukrishnan** [comment]
Sorry about that. I'd given a pull request to the sails-generate-auth and it got accepted recently. I guess it's yet to get updated in the npm module. I'll revert the documentation back to the original one with a note. 

Thanks for the info :)

**Comment by yedhukrishnan** [comment]
I've updated it :+1:

**Comment by jurajpetrik** [comment]
perfect,
Feel free to close this issue.
On a slightly related note, I want all of my app to be API only including user registration and login. I'm struggling with how to change AuthController for that.
I guess somewhere in here https://github.com/sails101/even-more-passport/blob/master/api/controllers/AuthController.js#L154-L164 I should return the token instead of redirecting? I'm not exactly sure where though.

**Comment by yedhukrishnan** [comment]
Why do u need login page if you are authorizing only using API key?

**Comment by jurajpetrik** [comment]
The user sends me his login and password through JSON I verify it's correct create a token and return it to him. With next requests he sends me this token so I can make sure he's logged in
I don't need a login page just a login REST method if that's what you mean

**Comment by yedhukrishnan** [comment]
In that case, instead of a login page, you can create an HTTP POST action which accepts the username and password and returns the bearer token if the credentials are valid.

Further requests can be made with the token.

**Comment by yedhukrishnan** [comment]
Better option is to have a POST action for registration which returns a token, and save the token for future requests. I don't think users need to authenticate with username and password once token is available, do they?

**Comment by jurajpetrik** [comment]
Yes, the part I'm having problem is how to call the passport with the username and passport and have it return the bearer token.

**Comment by yedhukrishnan** [comment]
It would look something similar to this:

```
login: function(req, res) {
    User.findOne({ username: req.body.username }, function(err, user) {
        Passport.findOne({ userID: user.id, password: hash(req.body.password) }, function(err, passport) {
             return res.json({ token: passport.token })
        });
    });
}
```

were hash is the function used to hash the password before saving to DB.

I am updating a better approach:

```
login: function(req, res) {
    User.findOne({ username: req.body.username }, function(err, user) {
        Passport.findOne({ userID: user.id }, function(err, passport) {
             /* compare the password in passport and the one received through req. if both are equal, return the token */
             return res.json({ token: passport.token })
        });
    });
}
```

**Comment by jurajpetrik** [comment]
I'm confused even more now,
I thought I would have to call passport.callback somehow like the example app does. 
How would the register function look like?

**Comment by yedhukrishnan** [comment]
Actually you can use the above code for registering, for API, there is no need for login. Once the user posts a username, password and password confirmation, you can create that user and return the token back.

I assume that you have only API access.

I will try to add the link to code here. I am currently working on it.

**Comment by yedhukrishnan** [comment]
Sorry for the delayed response. I've created a repo: [passport-api-auth](https://github.com/yedhukrishnan/passport-api-auth) which is cloned from this repo. See the changes in this commit: [Modify register to register user via API](https://github.com/yedhukrishnan/passport-api-auth/commit/20494e3dd5f0e13f10283c96d5cb63d5e8162388)

Here, we can create a user via register, by posting user data and it returns the API token. The token can be used for sending further requests.

**Comment by jurajpetrik** [comment]
login: function(req, res) {
      var email = req.query.email;
      var password = req.query.password;

      User.findOne({ email: req.query.email }, function(err, user) {
        if(err || !user){
          res.send('400',{error:"wrong email"});
          return;
        }
        Passport.findOne({ user: user.id}, function(err, passport) {
          passport.validatePassword(password, function(err, passwordIsCorrect){
            if(passwordIsCorrect){
              res.json({ token: passport.accessToken });
              return;
            }
            else{
              res.send('400',{error:"wrong password"});
              return;
            }
          });  
       });
      });
    },

**Comment by jurajpetrik** [comment]
This is what I ended up implementing.
Thanks very much for your guidance, I would be screwed without it :)

```
  login: function(req, res) {
  var email = req.query.email;
  var password = req.query.password;

  User.findOne({ email: req.query.email }, function(err, user) {
    if(err || !user){
      res.send('400',{error:"wrong email"});
      return;
    }
    Passport.findOne({ user: user.id}, function(err, passport) {
      passport.validatePassword(password, function(err, passwordIsCorrect){
        if(passwordIsCorrect){
          res.json({ token: passport.accessToken });
          return;
        }
        else{
          res.send('400',{error:"wrong password"});
          return;
        }
      });  
   });
  });
},

register: function (req, res) {
   req.query.provider = 'local';
   req.query.action = 'register';
   passport.callback(req, res, function (err, user) {
     if (err || !user) {
       res.send('400',{error:err});
       return;
     }
     Passport.findOne({ user: user.id}, function(err, passport) {
           res.json({ token: passport.accessToken });
     });
   });
 },
```

**Comment by yedhukrishnan** [comment]
That's great! I believe I can close this issue :)

**Comment by tommykennedy** [comment]
This is really a great help and it would be nice to see it on the main page. I searched for days until I came across. This information will really help those who want to build web and mobile apps
